# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://laurajjp.github.io/nbdevtutorial/"

git_url = "https://github.com/laurajjp/nbdevtutorial/tree/master/"

def custom_doc_links(name): return None
